<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>12&nbsp; Spatially Constrained Clustering - Hierarchical Methods – The Python Companion to Spatial Cluster Analysis with GeoDa</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./partitioned_spatial_clustering.html" rel="next">
<link href="./spatializing.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-485d01fc63b59abcd3ee1bf1e8e2748d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./hierarchical_spatial_clustering.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Spatially Constrained Clustering - Hierarchical Methods</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">The Python Companion to Spatial Cluster Analysis with GeoDa</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Creating_maps.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Creating Thematic Maps</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Multivariate_local.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Multivariate Local Spatial Clusters</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Density_cluster.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Density Based Clustering</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./PCA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Principal Component Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./MDS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Distance Preserving Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hierarchical_clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Hierarchical Clustering Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kmeans.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Partitioning Clustering Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kmedoids.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Advanced Clustering Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./spectral_clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Spectral Clustering</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./spatializing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Spatializing Classic Clustering Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hierarchical_spatial_clustering.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Spatially Constrained Clustering - Hierarchical Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./partitioned_spatial_clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Spatially Constrained Clustering - Partitioning Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cluster_validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Cluster Validation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bibliography.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#preliminaries" id="toc-preliminaries" class="nav-link active" data-scroll-target="#preliminaries"><span class="header-section-number">12.1</span> Preliminaries</a>
  <ul class="collapse">
  <li><a href="#import-required-modules" id="toc-import-required-modules" class="nav-link" data-scroll-target="#import-required-modules"><span class="header-section-number">12.1.1</span> Import Required Modules</a></li>
  <li><a href="#load-data" id="toc-load-data" class="nav-link" data-scroll-target="#load-data"><span class="header-section-number">12.1.2</span> Load Data</a></li>
  <li><a href="#variables" id="toc-variables" class="nav-link" data-scroll-target="#variables"><span class="header-section-number">12.1.3</span> Variables</a></li>
  <li><a href="#pygeoda-data-preparation" id="toc-pygeoda-data-preparation" class="nav-link" data-scroll-target="#pygeoda-data-preparation"><span class="header-section-number">12.1.4</span> Pygeoda Data Preparation</a></li>
  <li><a href="#pysal-spatial-weights" id="toc-pysal-spatial-weights" class="nav-link" data-scroll-target="#pysal-spatial-weights"><span class="header-section-number">12.1.5</span> PySAL Spatial Weights</a></li>
  <li><a href="#miscellaneous-arguments" id="toc-miscellaneous-arguments" class="nav-link" data-scroll-target="#miscellaneous-arguments"><span class="header-section-number">12.1.6</span> Miscellaneous Arguments</a></li>
  </ul></li>
  <li><a href="#schc" id="toc-schc" class="nav-link" data-scroll-target="#schc"><span class="header-section-number">12.2</span> SCHC</a>
  <ul class="collapse">
  <li><a href="#schc-with-scikit-learn" id="toc-schc-with-scikit-learn" class="nav-link" data-scroll-target="#schc-with-scikit-learn"><span class="header-section-number">12.2.1</span> SCHC with Scikit-Learn</a></li>
  </ul></li>
  <li><a href="#skater" id="toc-skater" class="nav-link" data-scroll-target="#skater"><span class="header-section-number">12.3</span> SKATER</a>
  <ul class="collapse">
  <li><a href="#additional-constraints-in-the-clustering" id="toc-additional-constraints-in-the-clustering" class="nav-link" data-scroll-target="#additional-constraints-in-the-clustering"><span class="header-section-number">12.3.1</span> Additional Constraints in the Clustering</a></li>
  </ul></li>
  <li><a href="#redcap" id="toc-redcap" class="nav-link" data-scroll-target="#redcap"><span class="header-section-number">12.4</span> REDCAP</a></li>
  <li><a href="#practice" id="toc-practice" class="nav-link" data-scroll-target="#practice"><span class="header-section-number">12.5</span> Practice</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-spatialhierarchical" class="quarto-section-identifier"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Spatially Constrained Clustering - Hierarchical Methods</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In this Chapter, we introduce methods to impose <em>hard</em> spatial constraints in a clustering procedure. We consider three approaches that use a hierarchical clustering logic: spatially constrained hierarchical clustering (SCHC), SKATER (Spatial Kluster Analysis by Tree Edge Removal), <span class="citation" data-cites="Assuncaoetal06">Assunçao et al. (<a href="bibliography.html#ref-Assuncaoetal06" role="doc-biblioref">2006</a>)</span>, and REDCAP (REgionalization with Dynamically Constrained Agglomerative clustering and Partitioning), <span class="citation" data-cites="Guo08">Guo (<a href="bibliography.html#ref-Guo08" role="doc-biblioref">2008</a>)</span>, <span class="citation" data-cites="GuoWang11">Guo and Wang (<a href="bibliography.html#ref-GuoWang11" role="doc-biblioref">2011</a>)</span>. These methods are covered in Chapter 10 of the <em>GeoDa Cluster Book</em>.</p>
<p>Other than a form of spatially constrained hierarchical clustering, spatially constrained clustering methods are not (yet) part of scikit-learn. The corresponding functionality from <code>GeoDa</code> is included in the <code>pygeoda</code> package. In addition, we also employ <code>AgglomerativeClustering</code> from <code>sklearn.cluster</code>, <code>StandardScaler</code> from <code>sklearn.preprocessing</code>, and the helper functions <code>ensure_datasets</code>, <code>cluster_stats</code>, <code>cluster_center</code>, <code>cluster_fit</code> and <code>cluster_map</code> from the <code>spatial-cluster-helper</code> package. We rely on <code>geopandas</code> and <code>numpy</code> for the basics, and use <code>libpysal.weights</code> to construct a contiguity matrix from a GeoDataFrame.</p>
<p>We also import <code>time</code> to compare the relative performance of the different implementations, as well as <code>warnings</code> to avoid some warning messages (suppressed by means of <code>filterwarnings</code>).</p>
<p>We continue with the <strong>ceara</strong> sample data set for the empirical illustration.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Required Packages">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Required Packages
</div>
</div>
<div class="callout-body-container callout-body">
<p>geopandas, numpy, time, warnings, sklearn.cluster, sklearn.preprocessing, pygeoda, libpysal.weights, spatial-cluster-helper</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Required Data Sets">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Required Data Sets
</div>
</div>
<div class="callout-body-container callout-body">
<p>ceara</p>
</div>
</div>
<section id="preliminaries" class="level2" data-number="12.1">
<h2 data-number="12.1" class="anchored" data-anchor-id="preliminaries"><span class="header-section-number">12.1</span> Preliminaries</h2>
<section id="import-required-modules" class="level3" data-number="12.1.1">
<h3 data-number="12.1.1" class="anchored" data-anchor-id="import-required-modules"><span class="header-section-number">12.1.1</span> Import Required Modules</h3>
<div id="e49b893f" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> geopandas <span class="im">as</span> gpd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> time</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.cluster <span class="im">import</span> AgglomerativeClustering</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> spatial_cluster_helper <span class="im">import</span> ensure_datasets, cluster_stats, <span class="op">\</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>              cluster_fit, cluster_center, cluster_map</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pygeoda</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> libpysal.weights <span class="im">as</span> weights</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-data" class="level3" data-number="12.1.2">
<h3 data-number="12.1.2" class="anchored" data-anchor-id="load-data"><span class="header-section-number">12.1.2</span> Load Data</h3>
<p>We read the data from the <code>ceara.shp</code> shape file and carry out a quick check of its contents. For this sample data, we use the argument <code>encoding = 'utf-8'</code> in the <code>read_file</code> function to account for the special characters in Brazilian Portuguese.</p>
<div id="a2bd865b" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Setting working folder:</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co">#path = "/your/path/to/data/"</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>path <span class="op">=</span> <span class="st">"./datasets/"</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Select the Ceará data:</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>shpfile <span class="op">=</span> <span class="st">"ceara/ceara.shp"</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the data:</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>ensure_datasets(shpfile, folder_path <span class="op">=</span> path)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>dfs <span class="op">=</span> gpd.read_file(path <span class="op">+</span> shpfile, encoding <span class="op">=</span> <span class="st">'utf-8'</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dfs.shape)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>dfs.head(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(184, 36)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">code7</th>
<th data-quarto-table-cell-role="th">mun_name</th>
<th data-quarto-table-cell-role="th">state_init</th>
<th data-quarto-table-cell-role="th">area_km2</th>
<th data-quarto-table-cell-role="th">state_code</th>
<th data-quarto-table-cell-role="th">micro_code</th>
<th data-quarto-table-cell-role="th">micro_name</th>
<th data-quarto-table-cell-role="th">inc_mic_4q</th>
<th data-quarto-table-cell-role="th">inc_zik_3q</th>
<th data-quarto-table-cell-role="th">inc_zik_2q</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">gdp</th>
<th data-quarto-table-cell-role="th">pop</th>
<th data-quarto-table-cell-role="th">gdpcap</th>
<th data-quarto-table-cell-role="th">popdens</th>
<th data-quarto-table-cell-role="th">zik_1q</th>
<th data-quarto-table-cell-role="th">ziq_2q</th>
<th data-quarto-table-cell-role="th">ziq_3q</th>
<th data-quarto-table-cell-role="th">zika_d</th>
<th data-quarto-table-cell-role="th">mic_d</th>
<th data-quarto-table-cell-role="th">geometry</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2300101.0</td>
<td>Abaiara</td>
<td>CE</td>
<td>180.833</td>
<td>23</td>
<td>23019</td>
<td>19ª Região Brejo Santo</td>
<td>0.000000</td>
<td>0.0</td>
<td>0.00</td>
<td>...</td>
<td>35974.0</td>
<td>10496.0</td>
<td>3.427</td>
<td>58.043</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>POLYGON ((5433729.65 9186242.97, 5433688.546 9...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2300150.0</td>
<td>Acarape</td>
<td>CE</td>
<td>130.002</td>
<td>23</td>
<td>23003</td>
<td>3ª Região Maracanaú</td>
<td>6.380399</td>
<td>0.0</td>
<td>0.00</td>
<td>...</td>
<td>68314.0</td>
<td>15338.0</td>
<td>4.454</td>
<td>117.983</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td>1.0</td>
<td>POLYGON ((5476916.288 9533405.667, 5476798.561...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2300200.0</td>
<td>Acaraú</td>
<td>CE</td>
<td>842.471</td>
<td>23</td>
<td>23012</td>
<td>12ª Região Acaraú</td>
<td>0.000000</td>
<td>0.0</td>
<td>1.63</td>
<td>...</td>
<td>309490.0</td>
<td>57551.0</td>
<td>5.378</td>
<td>68.312</td>
<td>0.0</td>
<td>1.0</td>
<td>0.0</td>
<td>1.0</td>
<td>0.0</td>
<td>POLYGON ((5294389.783 9689469.144, 5294494.499...</td>
</tr>
</tbody>
</table>

<p>3 rows × 36 columns</p>
</div>
</div>
</div>
<div id="22717139" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># the full set of variables</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">list</span>(dfs.columns))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>['code7', 'mun_name', 'state_init', 'area_km2', 'state_code', 'micro_code', 'micro_name', 'inc_mic_4q', 'inc_zik_3q', 'inc_zik_2q', 'inc_zik_1q', 'prim_care', 'ln_gdp', 'ln_pop', 'mobility', 'environ', 'housing', 'sanitation', 'infra', 'acu_zik_1q', 'acu_zik_2q', 'acu_zik_3q', 'pop_zikv', 'acu_mic_4q', 'pop_micro', 'lngdpcap', 'gdp', 'pop', 'gdpcap', 'popdens', 'zik_1q', 'ziq_2q', 'ziq_3q', 'zika_d', 'mic_d', 'geometry']</code></pre>
</div>
</div>
</section>
<section id="variables" class="level3" data-number="12.1.3">
<h3 data-number="12.1.3" class="anchored" data-anchor-id="variables"><span class="header-section-number">12.1.3</span> Variables</h3>
<p>We follow the empirical illustration in Chapter 10 of the <em>GeoDa Cluster Book</em> and select the following variables from the <strong>ceara</strong> sample data set:</p>
<div id="tbl-spatialcluster-vars" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-spatialcluster-vars-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;12.1: Spatial clustering variables
</figcaption>
<div aria-describedby="tbl-spatialcluster-vars-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Column Name</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">mobility</td>
<td style="text-align: left;">Mobility index</td>
</tr>
<tr class="even">
<td style="text-align: left;">environ</td>
<td style="text-align: left;">Environment index</td>
</tr>
<tr class="odd">
<td style="text-align: left;">housing</td>
<td style="text-align: left;">Housing index</td>
</tr>
<tr class="even">
<td style="text-align: left;">sanitation</td>
<td style="text-align: left;">Sanitation index</td>
</tr>
<tr class="odd">
<td style="text-align: left;">infra</td>
<td style="text-align: left;">Infrastructure index</td>
</tr>
<tr class="even">
<td style="text-align: left;">gdpcap</td>
<td style="text-align: left;">GDP per capita</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>We specify the variables in a list for later use.</p>
<div id="a0fea506" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>varlist <span class="op">=</span> [<span class="st">'mobility'</span>, <span class="st">'environ'</span>, <span class="st">'housing'</span>, <span class="st">'sanitation'</span>, <span class="st">'infra'</span>, <span class="st">'gdpcap'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="pygeoda-data-preparation" class="level3" data-number="12.1.4">
<h3 data-number="12.1.4" class="anchored" data-anchor-id="pygeoda-data-preparation"><span class="header-section-number">12.1.4</span> Pygeoda Data Preparation</h3>
<p><code>pygeoda</code> uses its own internal data format. It requires a few extra steps to convert a GeoDataFrame to this format. This is accomplished by means of the <code>open</code> command to which the GeoDataFrame (<code>dfs</code>) is passed.</p>
<p>In addition, we create queen contiguity weights using <code>queen_weights</code> and briefly check their characteristics. These weights are critical to obtain spatially constrained cluster results.</p>
<div id="8d74ec17" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>ceara_g <span class="op">=</span> pygeoda.<span class="bu">open</span>(dfs)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>queen_w <span class="op">=</span> pygeoda.queen_weights(ceara_g)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>queen_w</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>Weights Meta-data:
 number of observations:                  184
           is symmetric:                 True
               sparsity:  0.02953686200378072
        # min neighbors:                    1
        # max neighbors:                   13
       # mean neighbors:    5.434782608695652
     # median neighbors:                  5.0
           has isolates:                False</code></pre>
</div>
</div>
<p>We need the relevant variables in a <code>pygeoda</code> data format. This is accomplished in the same way as for a standard data frame, by selecting a subset with a list of variables (<code>varlist</code>). This yields the data object <code>data_g</code> that we will use in the <code>pygeoda</code> functions. However, because we will also use the various helper functions from the <code>spatial_cluster_helper</code> module, we will need the usual GeoDataFrame subset as well. We extract the variables as <code>data</code> (geo data frame) for future use.</p>
<div id="69584284" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>data_g <span class="op">=</span> ceara_g[varlist]</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> dfs[varlist]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="pysal-spatial-weights" class="level3" data-number="12.1.5">
<h3 data-number="12.1.5" class="anchored" data-anchor-id="pysal-spatial-weights"><span class="header-section-number">12.1.5</span> PySAL Spatial Weights</h3>
<p>The implementation of SCHC by means of scikit-learn requires a sparse array as an argument. The spatial weights created in <code>pygeoda</code> do not have such a property. Instead, we must rely on the <code>sparse</code> attribute that is part of a <code>PySAL</code> spatial weights object.</p>
<p>We use <code>libpysal.weights</code> to obtain a queen contiguity matrix from the GeoDataFrame <code>dfs</code>. Since only the contiguity information is used, we do not need to row-standardize the weights. If the <code>warningsfilter</code> was not set to <code>ignore</code>, this will yield some warnings. They can safely be ignored, but can also be suppressed with the code as shown in the import statements.</p>
<div id="3b941b43" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>wq <span class="op">=</span> weights.Queen.from_dataframe(dfs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="miscellaneous-arguments" class="level3" data-number="12.1.6">
<h3 data-number="12.1.6" class="anchored" data-anchor-id="miscellaneous-arguments"><span class="header-section-number">12.1.6</span> Miscellaneous Arguments</h3>
<p>We set the number of clusters to 12.</p>
<div id="f59081de" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>n_clusters <span class="op">=</span> <span class="dv">12</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Finally, we also compute the usual scaling factor as <code>nn</code>.</p>
<div id="8bba8ffb" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> data.shape[<span class="dv">0</span>]</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>nn <span class="op">=</span> np.sqrt((n<span class="op">-</span><span class="fl">1.0</span>)<span class="op">/</span>n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="schc" class="level2" data-number="12.2">
<h2 data-number="12.2" class="anchored" data-anchor-id="schc"><span class="header-section-number">12.2</span> SCHC</h2>
<p>The first method we consider is <em>spatially constrained hierarchical clustering</em>, or SCHC. This method proceeds in the same manner as hierarchical clustering (see <a href="hierarchical_clustering.html" class="quarto-xref">Chapter&nbsp;<span>7</span></a>), but the closest units are only merged when they are also contiguous, as defined by the spatial weights. This requires a continuous updating of the spatial weights information, carried out under the hood. The specific <code>pygeoda</code> method is <code>schc</code>. It takes the number of clusters (<code>n_clusters</code>), the spatial weights object (<code>queen_w</code>, from <code>pygeoda</code>), the variables in <code>pygeoda</code> format (<code>data_g</code>), and the linkage method, here set to <code>"ward"</code>.</p>
<p>The result is a <em>dictionary</em> that contains various measures of fit, as well as a cluster label for each observation. In contrast to what is the case for cluster computations in scikit-learn, the labels start at 1, not at 0.</p>
<p>We apply this for 12 clusters for the <strong>ceara</strong> variables and list the <code>keys</code> of the return object.</p>
<div id="3fc62191" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>t0 <span class="op">=</span> time.time()</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>ceara_clusters1 <span class="op">=</span> pygeoda.schc(n_clusters, queen_w, data_g, <span class="st">"ward"</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>t1 <span class="op">=</span> time.time()</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>tpygeoda <span class="op">=</span> t1 <span class="op">-</span> t0</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Time for pygeoda schc"</span>,tpygeoda)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(ceara_clusters1.keys())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Time for pygeoda schc 0.007565975189208984
dict_keys(['Total sum of squares', 'Within-cluster sum of squares', 'Total within-cluster sum of squares', 'Total between-cluster sum of squares', 'The ratio of between to total sum of squares', 'Clusters'])</code></pre>
</div>
</div>
<p>The cluster labels are contained in the <code>'Clusters'</code> item in the dictionary. We can extract them as <code>cluster_labels1</code> for use in our helper functions. For example, the helper function <code>cluster_stats</code> will return the cardinality of each cluster. To accomplish this, we need to make sure that <code>cluster_labels1</code> is a <code>numpy</code> array (hence, the application of <code>np.array</code>).</p>
<div id="13fc88bc" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>cluster_labels1 <span class="op">=</span> np.array(ceara_clusters1[<span class="st">'Clusters'</span>])</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>c_stats1 <span class="op">=</span> cluster_stats(cluster_labels1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Labels  Cardinality
      1           79
      2           48
      3           21
      4           17
      5            5
      6            4
      7            3
      8            2
      9            2
     10            1
     11            1
     12            1</code></pre>
</div>
</div>
<p>The remaining keys contain measures of fit. We can print them in a simple loop, excluding the last item (the cluster labels).</p>
<div id="72ecec01" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> key <span class="kw">in</span> <span class="bu">list</span>(ceara_clusters1.keys())[:<span class="op">-</span><span class="dv">1</span>]:  <span class="co"># Print all results except labels</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>key<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">round</span>(ceara_clusters1[key],<span class="dv">4</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Total sum of squares: 1098.0
Within-cluster sum of squares: [225.7318 168.248   93.8421  46.7944  18.098   11.0881   5.5954  16.9901
   2.0036   0.       0.       0.    ]
Total within-cluster sum of squares: 588.3915
Total between-cluster sum of squares: 509.6085
The ratio of between to total sum of squares: 0.4641</code></pre>
</div>
</div>
<p>Alternatively, we can also apply our <code>cluster_fit</code> helper function. The results are identical, as long as we set the <code>correct</code> argument to <code>True</code>. This ensures that the same standardization is used as in <code>GeoDa</code> (the default in scikit-learn is a variance computation without degrees of freedom correction).</p>
<div id="91d85f5a" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>fit1 <span class="op">=</span> cluster_fit(data, cluster_labels1, n_clusters, </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>                   correct <span class="op">=</span> <span class="va">True</span>, printopt <span class="op">=</span> <span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Total Sum of Squares (TSS): 1098.0
Within-cluster Sum of Squares (WSS) for each cluster: [225.732 168.248  93.842  46.794  18.098  11.088   5.595  16.99    2.004
   0.      0.      0.   ]
Total Within-cluster Sum of Squares (WSS): 588.391
Between-cluster Sum of Squares (BSS): 509.609
Ratio of BSS to TSS: 0.464</code></pre>
</div>
</div>
<p>The <code>cluster_center</code> helper function will list the cluster mean and median for each variable.</p>
<div id="ca61e272" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>clust_means1, clust_medians1 <span class="op">=</span> cluster_center(data, cluster_labels1)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Cluster Means:</span><span class="ch">\n</span><span class="st">"</span>, np.<span class="bu">round</span>(clust_means1, <span class="dv">3</span>))</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Cluster Medians:</span><span class="ch">\n</span><span class="st">"</span>, np.<span class="bu">round</span>(clust_medians1, <span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cluster Means:
          mobility  environ  housing  sanitation  infra  gdpcap
cluster                                                       
1           0.965    0.891    0.846       0.672  0.524   4.508
2           0.952    0.844    0.795       0.597  0.504   4.483
3           0.950    0.879    0.844       0.576  0.441   6.834
4           0.951    0.758    0.844       0.649  0.588   4.821
5           0.968    0.815    0.792       0.581  0.438   4.246
6           0.833    0.766    0.818       0.792  0.574  12.600
7           0.992    0.942    0.824       0.870  0.625   6.823
8           0.974    0.657    0.781       0.823  0.693   5.432
9           0.859    0.687    0.722       0.584  0.417   4.644
10          0.957    0.966    0.857       0.593  0.357  40.018
11          0.936    0.789    0.794       0.545  0.425  27.625
12          0.951    0.824    0.771       0.573  0.443  25.464
Cluster Medians:
          mobility  environ  housing  sanitation  infra  gdpcap
cluster                                                       
1           0.968    0.895    0.848       0.669  0.523   4.319
2           0.953    0.871    0.794       0.572  0.498   4.120
3           0.954    0.896    0.836       0.575  0.427   5.837
4           0.950    0.758    0.845       0.636  0.590   4.214
5           0.967    0.805    0.804       0.594  0.477   4.285
6           0.835    0.766    0.824       0.799  0.583  11.557
7           0.993    0.932    0.829       0.885  0.606   4.488
8           0.974    0.657    0.781       0.823  0.693   5.432
9           0.859    0.687    0.722       0.584  0.417   4.644
10          0.957    0.966    0.857       0.593  0.357  40.018
11          0.936    0.789    0.794       0.545  0.425  27.625
12          0.951    0.824    0.771       0.573  0.443  25.464</code></pre>
</div>
</div>
<p>Finally, as before, we can use <code>cluster_map</code> to create a unique values map for the clusters.</p>
<div id="cell-fig-schc-cluster" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>cluster_map(dfs, cluster_labels1, figsize<span class="op">=</span>(<span class="dv">4</span>, <span class="dv">4</span>), </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>            title<span class="op">=</span><span class="st">""</span>, cmap<span class="op">=</span><span class="st">'tab20'</span>, legend_fontsize<span class="op">=</span><span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-schc-cluster" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-schc-cluster-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="hierarchical_spatial_clustering_files/figure-html/fig-schc-cluster-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-schc-cluster-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.1: Spatially constrained hierarchical clustering
</figcaption>
</figure>
</div>
</div>
</div>
<section id="schc-with-scikit-learn" class="level3" data-number="12.2.1">
<h3 data-number="12.2.1" class="anchored" data-anchor-id="schc-with-scikit-learn"><span class="header-section-number">12.2.1</span> SCHC with Scikit-Learn</h3>
<p>The <code>AgglomerativeClustering</code> functionality in <code>sklearn.cluster</code> includes an option for a so-called <em>structured</em> approach. It imposes prior constraints through a <code>connectivity</code> argument, which takes a sparse CSR array. In practice, this can yield a spatially constrained clustering solution, although it is not directly referred to as such (the constraints are generic). For spatial constraints, we can readily obtain an array in the proper sparse format by applying the <code>sparse</code> method to a <code>PySAL</code> spatial weights object. In our application, this is <code>wq.sparse</code>. Note that the <code>sparse</code> method does <strong>not</strong> work for the spatial weights object created by <code>pygeoda</code> (i.e., <code>queen_w</code> in our example).</p>
<p>The call to <code>AgglomerativeClustering</code> is structured in the same way as in <a href="hierarchical_clustering.html" class="quarto-xref">Chapter&nbsp;<span>7</span></a>. First, <code>StandardScaler</code> is used to <code>fit_transform</code> the cluster variables, followed by a scaling for compatibility. An instance of the <code>AgglomerativeClustering</code> class is created as <code>agg_clust</code>, which has all the standard arguments, with the addition of <code>connectivity = wq.sparse</code>. After the <code>fit</code> method is applied, the cluster labels (<code>cluster_labels1a</code>) are extracted from <code>agg_clust.labels_</code>. We then apply the <code>cluster_stats</code> helper function. Whereas the ordering of the cluster cardinalities is different from that provided by <code>pygeoda</code>, the values are identical.</p>
<div id="0bbc022b" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>method <span class="op">=</span> <span class="st">'ward'</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>t0 <span class="op">=</span> time.time()</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>X0 <span class="op">=</span> StandardScaler().fit_transform(data)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> X0 <span class="op">*</span> nn</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>agg_clust <span class="op">=</span> AgglomerativeClustering(n_clusters<span class="op">=</span>n_clusters, </span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>                                    connectivity <span class="op">=</span> wq.sparse,</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>                                    linkage<span class="op">=</span>method, compute_distances<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>agg_clust.fit(X)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>cluster_labels1a <span class="op">=</span> agg_clust.labels_</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>cl1a <span class="op">=</span> cluster_stats(cluster_labels1a)</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>t1 <span class="op">=</span> time.time()</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>tsklearn <span class="op">=</span> t1 <span class="op">-</span> t0</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Time for scikit-learn schc "</span>,tsklearn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Labels  Cardinality
      0           48
      1           21
      2            2
      3           17
      4           79
      5            3
      6            4
      7            1
      8            1
      9            2
     10            5
     11            1

Time for scikit-learn schc  0.00432586669921875</code></pre>
</div>
</div>
<p>The cluster fit properties are the same as well, as is the resulting cluster map.</p>
<div id="ed6c7797" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>fit1a <span class="op">=</span> cluster_fit(data,cluster_labels1a,n_clusters,</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>                    correct<span class="op">=</span><span class="va">True</span>,printopt<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Total Sum of Squares (TSS): 1098.0
Within-cluster Sum of Squares (WSS) for each cluster: [168.248  93.842  16.99   46.794 225.732   5.595  11.088   0.      0.
   2.004  18.098   0.   ]
Total Within-cluster Sum of Squares (WSS): 588.391
Between-cluster Sum of Squares (BSS): 509.609
Ratio of BSS to TSS: 0.464</code></pre>
</div>
</div>
<div id="cell-fig-schc-cluster-scikit" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>cluster_map(dfs, cluster_labels1a, figsize<span class="op">=</span>(<span class="dv">4</span>,<span class="dv">4</span>), </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>            title<span class="op">=</span><span class="st">""</span>, cmap<span class="op">=</span><span class="st">'tab20'</span>, legend_fontsize<span class="op">=</span><span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-schc-cluster-scikit" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-schc-cluster-scikit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="hierarchical_spatial_clustering_files/figure-html/fig-schc-cluster-scikit-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-schc-cluster-scikit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.2: Spatially constrained hierarchical cluster (scikit-learn)
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="skater" class="level2" data-number="12.3">
<h2 data-number="12.3" class="anchored" data-anchor-id="skater"><span class="header-section-number">12.3</span> SKATER</h2>
<p>In contrast to the agglomerative SCHC, SKATER is a <em>divisive</em> hierarchical approach. It is based on a reduction of the graph structure implied by the spatial weights to a <em>minimum spanning tree</em>, based on the inter-observation dissimilarity. The original graph is essentially a weighted form of the spatial weights matrix, where the existence of a contiguity between two observations is weighted by their dissimilarity. From the initial minimum spanning tree, the SKATER algorithm proceeds by finding optimal <em>cuts</em> in the tree, which each form a subcluster. This process continues until the desired number of clusters is found.</p>
<p>One downside of this approach is that observations are trapped in subclusters and cannot further be swapped. Technical details are provided in Chapter 10 of the <em>GeoDa Cluster Book</em>.</p>
<p>The algorithm is invoked with the <code>skater</code> method of <code>pygeoda</code>. This again requires the number of clusters (<code>n_clusters</code>), the spatial weights (<code>queen_w</code>) and the <code>pygeoda</code> variables (<code>data_g</code>) as arguments. The return object is a dictionary with the same structure as before.</p>
<p>We use the helper functions to generate the cluster cardinality, cluster fit, cluster centers and cluster map.</p>
<p>For simplicity, all commands are combined.</p>
<div id="5b5ff8de" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>t0 <span class="op">=</span> time.time()</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>ceara_clusters2 <span class="op">=</span> pygeoda.skater(n_clusters, queen_w, data_g)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>t1 <span class="op">=</span> time.time()</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>tskater <span class="op">=</span> t1 <span class="op">-</span> t0</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Time for pygeoda skater "</span>,tskater)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>cluster_labels2 <span class="op">=</span> np.array(ceara_clusters2[<span class="st">'Clusters'</span>])</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>cl2 <span class="op">=</span> cluster_stats(cluster_labels2)</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>fit2 <span class="op">=</span> cluster_fit(data, cluster_labels2, n_clusters,</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>                   correct <span class="op">=</span> <span class="va">True</span>, printopt <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>clust_means2, clust_medians2 <span class="op">=</span> cluster_center(data, cluster_labels2)</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Cluster Means:</span><span class="ch">\n</span><span class="st">"</span>, np.<span class="bu">round</span>(clust_medians2, <span class="dv">3</span>))</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Cluster Medians:</span><span class="ch">\n</span><span class="st">"</span>, np.<span class="bu">round</span>(clust_medians2, <span class="dv">3</span>))</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the clusters</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Time for pygeoda skater  0.02781391143798828
 Labels  Cardinality
      1          107
      2           41
      3           15
      4            4
      5            4
      6            3
      7            3
      8            3
      9            1
     10            1
     11            1
     12            1

Total Sum of Squares (TSS): 1098.0
Within-cluster Sum of Squares (WSS) for each cluster: [398.019 135.799  48.297  11.088   9.206   9.127   5.956   5.595   0.
   0.      0.      0.   ]
Total Within-cluster Sum of Squares (WSS): 623.089
Between-cluster Sum of Squares (BSS): 474.911
Ratio of BSS to TSS: 0.433
Cluster Means:
          mobility  environ  housing  sanitation  infra  gdpcap
cluster                                                       
1           0.966    0.880    0.844       0.638  0.537   4.152
2           0.954    0.879    0.807       0.594  0.490   4.598
3           0.948    0.882    0.835       0.544  0.414   6.760
4           0.835    0.766    0.824       0.799  0.583  11.557
5           0.963    0.708    0.751       0.544  0.471   4.263
6           0.966    0.957    0.906       0.671  0.566   5.837
7           0.885    0.687    0.730       0.622  0.427   5.110
8           0.993    0.932    0.829       0.885  0.606   4.488
9           0.936    0.789    0.794       0.545  0.425  27.625
10          0.983    0.644    0.865       0.858  0.859   5.578
11          0.957    0.966    0.857       0.593  0.357  40.018
12          0.951    0.824    0.771       0.573  0.443  25.464
Cluster Medians:
          mobility  environ  housing  sanitation  infra  gdpcap
cluster                                                       
1           0.966    0.880    0.844       0.638  0.537   4.152
2           0.954    0.879    0.807       0.594  0.490   4.598
3           0.948    0.882    0.835       0.544  0.414   6.760
4           0.835    0.766    0.824       0.799  0.583  11.557
5           0.963    0.708    0.751       0.544  0.471   4.263
6           0.966    0.957    0.906       0.671  0.566   5.837
7           0.885    0.687    0.730       0.622  0.427   5.110
8           0.993    0.932    0.829       0.885  0.606   4.488
9           0.936    0.789    0.794       0.545  0.425  27.625
10          0.983    0.644    0.865       0.858  0.859   5.578
11          0.957    0.966    0.857       0.593  0.357  40.018
12          0.951    0.824    0.771       0.573  0.443  25.464</code></pre>
</div>
</div>
<div id="cell-fig-skater" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>cluster_map(dfs, cluster_labels2, figsize <span class="op">=</span> (<span class="dv">4</span>, <span class="dv">4</span>), </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>            title<span class="op">=</span><span class="st">""</span>, cmap<span class="op">=</span><span class="st">'tab20'</span>, legend_fontsize<span class="op">=</span><span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-skater" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-skater-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="hierarchical_spatial_clustering_files/figure-html/fig-skater-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-skater-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.3: SKATER spatially constrained clustering
</figcaption>
</figure>
</div>
</div>
</div>
<section id="additional-constraints-in-the-clustering" class="level3" data-number="12.3.1">
<h3 data-number="12.3.1" class="anchored" data-anchor-id="additional-constraints-in-the-clustering"><span class="header-section-number">12.3.1</span> Additional Constraints in the Clustering</h3>
<p><code>GeoDa</code> offers the option to provide a constraint on the cluster size. This is typically expressed as a function of a spatially extensive variable, such as population in the Ceará example. This additional constraint ensures that no cluster contains less than the set limit. In practice, this is often needed when building regions to report rates on rare diseases to protect privacy. Note that the specified constraints may sometimes conflict with the desired number of clusters, in the sense that there is no solution that satisfies both the number of clusters and the minimum size constraint. In that case, the largest number of possible clusters that satisfy the constraint is given as the solution.</p>
<p>Even though there is no explicit option to provide the <em>number</em> of cluster elements as the constraint, this can readily be accomplished by creating an additional <em>constant</em> variable equal to 1 for all observations. The constraint can then be expressed by selecting this constant variable and setting the number of observations as the value for the constraint (the sum of all the <code>1</code> values).</p>
<p>A contraint is implemented in <code>pygeoda</code> by means of the <code>bound_variable</code> and <code>min_bound</code> arguments. Similar to the example in Chapter 10 of the <em>GeoDa Cluster Book</em>, we use population (<code>pop</code>) to set the bound at a minimum of 10% of the overall population. In all other respects, the approach remains the same as the unconstrained solution.</p>
<p>We again group all commands.</p>
<div id="ccfb4e40" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>t0 <span class="op">=</span> time.time()</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>ceara_clusters3 <span class="op">=</span> pygeoda.skater(n_clusters, queen_w, data_g, </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>                        bound_variable <span class="op">=</span> dfs[<span class="st">'pop'</span>], </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>                        min_bound <span class="op">=</span> dfs[<span class="st">'pop'</span>].<span class="bu">sum</span>()<span class="op">/</span><span class="dv">10</span>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>t1 <span class="op">=</span> time.time()</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>tskaterc <span class="op">=</span> t1 <span class="op">-</span> t0</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Time for pygeoda constrained skater "</span>,tskaterc)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>cluster_labels3 <span class="op">=</span> np.array(ceara_clusters3[<span class="st">'Clusters'</span>])</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>cl3 <span class="op">=</span> cluster_stats(cluster_labels3)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>fit3 <span class="op">=</span> cluster_fit(data, cluster_labels3, n_clusters,</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>                   correct <span class="op">=</span> <span class="va">True</span>, printopt <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>clust_means3, clust_medians3 <span class="op">=</span> cluster_center(data, cluster_labels3)</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Cluster Means:</span><span class="ch">\n</span><span class="st">"</span>, np.<span class="bu">round</span>(clust_means3, <span class="dv">3</span>))</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Cluster Medians:</span><span class="ch">\n</span><span class="st">"</span>, np.<span class="bu">round</span>(clust_medians3, <span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Time for pygeoda constrained skater  0.01644420623779297
 Labels  Cardinality
      1           43
      2           40
      3           36
      4           32
      5           26
      6            7

Total Sum of Squares (TSS): 1098.0
Within-cluster Sum of Squares (WSS) for each cluster: [156.507 172.008 158.72  113.536 208.516  43.745]
Total Within-cluster Sum of Squares (WSS): 853.033
Between-cluster Sum of Squares (BSS): 244.967
Ratio of BSS to TSS: 0.223
Cluster Means:
          mobility  environ  housing  sanitation  infra  gdpcap
cluster                                                       
1           0.964    0.884    0.841       0.644  0.532   4.562
2           0.956    0.857    0.797       0.617  0.495   5.292
3           0.961    0.817    0.836       0.645  0.535   4.485
4           0.964    0.880    0.844       0.711  0.544   4.601
5           0.946    0.861    0.830       0.566  0.451   8.434
6           0.851    0.742    0.785       0.715  0.508   9.475
Cluster Medians:
          mobility  environ  housing  sanitation  infra  gdpcap
cluster                                                       
1           0.970    0.896    0.845       0.607  0.537   4.097
2           0.954    0.878    0.803       0.591  0.488   4.635
3           0.963    0.828    0.836       0.625  0.547   4.120
4           0.968    0.892    0.849       0.711  0.535   4.417
5           0.949    0.870    0.831       0.545  0.450   5.300
6           0.845    0.741    0.795       0.710  0.497   7.675</code></pre>
</div>
</div>
<div id="cell-fig-skater-bounds" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>cluster_map(dfs, cluster_labels3, figsize<span class="op">=</span>(<span class="dv">4</span>, <span class="dv">4</span>), </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>            title<span class="op">=</span><span class="st">""</span>, cmap<span class="op">=</span><span class="st">'tab20'</span>, legend_fontsize<span class="op">=</span><span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-skater-bounds" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-skater-bounds-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="hierarchical_spatial_clustering_files/figure-html/fig-skater-bounds-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-skater-bounds-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.4: SKATER with minimum population bounds
</figcaption>
</figure>
</div>
</div>
</div>
<p>Note how even though we set the number of clusters to 12, only a solution with six clusters could be obtained such that the minimum population requirement is satisfied. Also, the overall fit of the solution is seriously deteriorated, to a BSS/TSS ratio of 0.223, compared to the original 0.433.</p>
</section>
</section>
<section id="redcap" class="level2" data-number="12.4">
<h2 data-number="12.4" class="anchored" data-anchor-id="redcap"><span class="header-section-number">12.4</span> REDCAP</h2>
<p>The final hierarchical method covered in Chapter 10 of the <em>GeoDa Cluster Book</em> is REDCAP, which is a combination of an agglomerative approach with the use of a minimum spanning tree. Several variants of the method are available, combining a type of hierarchical clustering linkage with the way the neighbor structure is updated (for full details, see the <em>GeoDa Cluster Book</em> and the detailed <code>pygeoda</code> documentation). Of all the combinations, five are supported by <code>pygeoda</code>:</p>
<ul>
<li><code>firstorder-singlelinkage</code></li>
<li><code>fullorder-singlelinkage</code></li>
<li><code>fullorder-averagelinkage</code></li>
<li><code>fullorder-completelinkage</code></li>
<li><code>fullorder-wardlinkage</code></li>
</ul>
<p>Here, as in Chapter 10 of the <em>GeoDa Cluster Book</em>, we will illustrate the <code>fullorder-wardlinkage</code> method, which is passed as the <code>method</code> argument to the <code>redcap</code> function. Everything else operates as before. Again, we combine all commands.</p>
<div id="722201b9" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>t0 <span class="op">=</span> time.time()</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>ceara_clusters4 <span class="op">=</span> pygeoda.redcap(n_clusters, queen_w, data_g, </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>                            method <span class="op">=</span> <span class="st">'fullorder-wardlinkage'</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>t1 <span class="op">=</span> time.time()</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Time for pygeoda redcap "</span>,t1 <span class="op">-</span> t0)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>cluster_labels4 <span class="op">=</span> np.array(ceara_clusters4[<span class="st">'Clusters'</span>])</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>cl4 <span class="op">=</span> cluster_stats(cluster_labels4)</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>fit4 <span class="op">=</span> cluster_fit(data, cluster_labels4, n_clusters,</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>                   correct <span class="op">=</span> <span class="va">True</span>, printopt <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>clust_means4, clust_medians4 <span class="op">=</span> cluster_center(data, cluster_labels4)</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Cluster Means:</span><span class="ch">\n</span><span class="st">"</span>, np.<span class="bu">round</span>(clust_means4, <span class="dv">3</span>))</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Cluster Medians:</span><span class="ch">\n</span><span class="st">"</span>, np.<span class="bu">round</span>(clust_medians4, <span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Time for pygeoda redcap  0.031903982162475586
 Labels  Cardinality
      1           77
      2           52
      3           21
      4           16
      5            5
      6            3
      7            3
      8            2
      9            2
     10            1
     11            1
     12            1

Total Sum of Squares (TSS): 1098.0
Within-cluster Sum of Squares (WSS) for each cluster: [214.614 173.74   63.005  66.063  38.299   9.602   5.595  16.99    2.004
   0.      0.      0.   ]
Total Within-cluster Sum of Squares (WSS): 589.912
Between-cluster Sum of Squares (BSS): 508.088
Ratio of BSS to TSS: 0.463
Cluster Means:
          mobility  environ  housing  sanitation  infra  gdpcap
cluster                                                       
1           0.966    0.894    0.847       0.675  0.526   4.527
2           0.951    0.842    0.793       0.583  0.495   4.974
3           0.952    0.762    0.839       0.626  0.571   4.646
4           0.950    0.887    0.858       0.603  0.440   6.011
5           0.857    0.777    0.809       0.749  0.548  15.173
6           0.969    0.829    0.777       0.632  0.387   4.390
7           0.992    0.942    0.824       0.870  0.625   6.823
8           0.974    0.657    0.781       0.823  0.693   5.432
9           0.859    0.687    0.722       0.584  0.417   4.644
10          0.958    0.973    0.928       0.798  0.647   3.884
11          0.936    0.789    0.794       0.545  0.425  27.625
12          0.957    0.966    0.857       0.593  0.357  40.018
Cluster Medians:
          mobility  environ  housing  sanitation  infra  gdpcap
cluster                                                       
1           0.969    0.896    0.848       0.672  0.523   4.369
2           0.952    0.864    0.793       0.564  0.495   4.243
3           0.956    0.758    0.842       0.609  0.569   4.127
4           0.956    0.906    0.856       0.594  0.425   5.300
5           0.845    0.791    0.823       0.784  0.561  15.132
6           0.968    0.805    0.763       0.642  0.400   4.313
7           0.993    0.932    0.829       0.885  0.606   4.488
8           0.974    0.657    0.781       0.823  0.693   5.432
9           0.859    0.687    0.722       0.584  0.417   4.644
10          0.958    0.973    0.928       0.798  0.647   3.884
11          0.936    0.789    0.794       0.545  0.425  27.625
12          0.957    0.966    0.857       0.593  0.357  40.018</code></pre>
</div>
</div>
<div id="cell-fig-redcap" class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>cluster_map(dfs, cluster_labels4, figsize<span class="op">=</span>(<span class="dv">4</span>, <span class="dv">4</span>), </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>            title<span class="op">=</span><span class="st">""</span>, cmap<span class="op">=</span><span class="st">'tab20'</span>, legend_fontsize<span class="op">=</span><span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-redcap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-redcap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="hierarchical_spatial_clustering_files/figure-html/fig-redcap-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-redcap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.5: REDCAP spatially constrained clustering
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="practice" class="level2" data-number="12.5">
<h2 data-number="12.5" class="anchored" data-anchor-id="practice"><span class="header-section-number">12.5</span> Practice</h2>
<p>The three spatially constrained hierarchical clustering methods can be applied to any of the data sets used in the previous Chapters to assess the effect of the constraint. In particular, it provides a way to quantify the trade-off between the non-spatial and spatial perspective.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Assuncaoetal06" class="csl-entry" role="listitem">
Assunçao, Renato M., M. C. Neves, G. Câmara, and C. Da Costa Freitas. 2006. <span>“Efficient Regionalization Techniques for Socio-Economic Geographical Units Using Minimum Spanning Trees.”</span> <em>International Journal of Geographical Information Science</em> 20: 797–811.
</div>
<div id="ref-Guo08" class="csl-entry" role="listitem">
Guo, Diansheng. 2008. <span>“Regionalization with Dynamically Constrained Agglomerative Clustering and Partitioning (<span>REDCAP</span>).”</span> <em>International Journal of Geographical Information Science</em> 22: 801–23.
</div>
<div id="ref-GuoWang11" class="csl-entry" role="listitem">
Guo, Diansheng, and Hu Wang. 2011. <span>“Automatic Region Building for Spatial Analysis.”</span> <em>Transactions in <span>GIS</span></em> 15: 29–45.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./spatializing.html" class="pagination-link" aria-label="Spatializing Classic Clustering Methods">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Spatializing Classic Clustering Methods</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./partitioned_spatial_clustering.html" class="pagination-link" aria-label="Spatially Constrained Clustering - Partitioning Methods">
        <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Spatially Constrained Clustering - Partitioning Methods</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Copyright 2025 GeoDa Press LLC, All Rights Reserved</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>